name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Chequear el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Docker para usar el demonio
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Autenticarse en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Construir la imagen Docker
    - name: Build Docker image
      run: |
        docker build -t myapp:${{ github.sha }} .

    # 5. Publicar la imagen en Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker tag myapp:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

    